config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == ENV["sidekiq_username"] && password == ENV["sidekiq_password"]
    end
  end
  mount Sidekiq::Web, at: "/sidekiq"

  get "discourse/sso" => 'discourse#sso'

  get "login", to: redirect("/ui/sessions/new")
  get "logout", to: redirect("/ui/sessions/destroy")
  get "password_reset/:token", to: redirect("/ui/password_reset/%{token}")

  namespace "ui" do
    get "/", to: redirect("/ui/users")

    get "/policy", to: "static#policy"

    constraints id: /[^\/]+/ do
      # Explicitly override to allow usernames with dots.
      # See:https://stackoverflow.com/questions/5369654/why-do-routes-with-a-dot-in-a-parameter-fail-to-match
      resources :users, as: "users" do
        member do
          get :delete
          get :edit
          get :secrets
        end
        collection do
          get :post_delete
        end
      end
    end

    resources :devices, as: "devices" do
      member do
        get :edit
        get :delete
        get :download
        get :upload
        post :upload, to: "devices#upload_readings"
        post :download, to: "devices#download_confirm"
      end
      collection do
        get :register
        get :new
        post :create
        get :onboarding
        post :onboarding, to: "devices#onboarding_create"
      end
    end

    resources :experiments, as: "experiments" do
      member do
        get :readings
        get :delete
      end
    end

    get "sessions/destroy", to: "sessions#destroy"
    resources :sessions, as: "sessions"
    post 'change_password', to: 'sessions#change_password', as: 'change_password'
    get 'password_reset/:token', to: 'sessions#password_reset_landing', as: 'password_reset'
  end

  api_version(module: "V1", path: { value: "v1" }, header: {name: "Accept", value: "application/vnd.smartcitizen; version=1"}, defaults: { format: :json }) do
    resources :devices
  end

  api_version(module: "V0", path: {value: "v0"}, header: {name: "Accept", value: "application/vnd.smartcitizen; version=0"}, default: true, defaults: { format: :json }) do
    # devices
    resources :devices do
      member do
        resources :readings, only: [:index, :create] do
          get 'csv_archive', on: :collection
        end
      end
      get 'world_map', on: :collection
      get 'fresh_world_map', on: :collection
    end
    # readings
    match "add" => "readings#legacy_create", via: [:get, :post, :patch, :put]
    match "datetime" => "readings#datetime", via: [:get, :post, :patch, :put]

    resources :sensors, except: [:destroy]
    resources :components, only: [:show, :index]
    resources :sessions, only: :create
    resources :experiments

    resources :tag_sensors
    resources :tags
    resources :measurements

    constraints id: /[^\/]+/ do
      # Explicitly override to allow usernames with dots.
      # See:https://stackoverflow.com/questions/5369654/why-do-routes-with-a-dot-in-a-parameter-fail-to-match
      resources :users
    end
    resources :password_resets, only: [:show, :create, :update]
    resources :oauth_applications, path: 'applications'
    get :forward, to: "forwarding#authorize"

    resources :me, only: [:index] do
      patch '/' => 'me#update', on: :collection
      put '/' => 'me#update', on: :collection
      delete '/' => 'me#destroy', on: :collection
    end

    # onboarding process
    namespace :onboarding do
      get 'device', to: 'orphan_devices#show'
      post 'device', to: 'orphan_devices#create'
      patch 'device', to: 'orphan_devices#update'
      post 'user', to: 'device_registrations#find_user'
      post 'register', to: 'device_registrations#register_device'
    end

    get "discourse/sso" => 'discourse#sso'
    get 'search' => 'static#search'
    get 'metrics' => 'static#metrics'
    # use_doorkeeper
    # root to: 'static#home'
    get '/', to: 'static#home'
    get '/version', to: "static#version"
    get "/404" => "errors#not_found"
    get "/500" => "errors#exception"
    get "/test_error" => "errors#test_error"

    # Active Storage cannot show the correct url if using catchall matchers
    # https://github.com/rails/rails/issues/31228
    # Disable until a solution is found
    #match "*path", to: "errors#not_found", via: :all
  end

  # get '*path', :to => redirect("/v0/%{path}")
  # root to: redirect('/v0')

end

app/models/device.rb
# This is an SCK (referred to as a 'Kit' in the frontend).
# It's called Device and not Kit or SCK because it's expected that the platform
# will support different kinds of hardware in the future (phones, arduino etc).

require 'open-uri'
require 'geohash'

class Device < ActiveRecord::Base

  EXPOSURE_VALUES = %w{indoor outdoor}
  HARDWARE_VERSION_OVERRIDE_VALUES = %w{1 1.1}

  default_scope { with_active_state }

  include ActiveModel::Dirty
  include Workflow
  include WorkflowActiverecord
  include ArchiveWorkflow
  include PgSearch::Model
  include CountryMethods

  multisearchable :against => [:name, :description, :city, :country_name], if: :active?

  belongs_to :owner, class_name: 'User'
  belongs_to :forwarding_destination, optional: true

  has_many :devices_tags, dependent: :destroy
  has_many :tags, through: :devices_tags
  has_many :components, dependent: :destroy
  has_many :sensors, through: :components
  has_one :postprocessing, dependent: :destroy
  has_many :ingest_errors, dependent: :destroy

  has_and_belongs_to_many :experiments

  accepts_nested_attributes_for :postprocessing, update_only: true

  validates_presence_of :name
  validates_presence_of :owner, on: :create
  #validates_uniqueness_of :name, scope: :owner_id, on: :create

  validates_uniqueness_of :device_token, allow_nil: true

  validates_format_of :mac_address,
    with: /\A([0-9a-fA-F]{2}[:-]){5}[0-9a-fA-F]{2}\z/, allow_nil: true

  validates_inclusion_of :exposure, in: EXPOSURE_VALUES, allow_nil: true

  before_save :nullify_other_mac_addresses, if: :mac_address
  before_save :truncate_and_fuzz_location!, if: :location_changed?
  before_save :calculate_geohash
  after_validation :do_geocoding

  store_accessor :location,
    :address,
    :city,
    :postal_code,
    :state_name,
    :state_code,
    :country_code

  store_accessor :meta,
    :elevation,
    :exposure,
    :firmware_version,
    :smart_cal,
    :debug_push,
    :enclosure_type

  before_save :set_state

  reverse_geocoded_by :latitude, :longitude do |obj, results|
    # Nominatim has a quota of 1 req / second
    if geo = results.first
      obj.address = geo.address
      obj.city = geo.city
      obj.postal_code = geo.postal_code
      obj.state_name = geo.state
      obj.state_code = geo.state_code
      obj.country_code = geo.country_code
    end
  end

  scope :for_user, ->(authorized_user=nil) {
    privacy_conditions = if authorized_user && authorized_user.is_admin?
                           []
                         elsif authorized_user
                           ["(is_private IS NOT true AND is_test IS NOT TRUE) OR owner_id = ?", authorized_user.id]
                         else
                           ["is_private IS NOT true AND is_test IS NOT TRUE"]
                         end
    where(privacy_conditions)
  }

  scope :by_last_reading, -> {
    order("last_reading_at DESC NULLS LAST, created_at DESC")
  }


  scope :for_world_map, ->(authorized_user=nil) {
    for_user(authorized_user).
    where.not(latitude: nil).
    where.not(last_reading_at: nil).
    where(is_test: false).
    includes(:owner, :tags)
  }

  def self.ransackable_attributes(auth_object = nil)
    if auth_object == :admin
      # admin can ransack on every attribute
      self.authorizable_ransackable_attributes
    else
      ["id", "name", "description", "created_at", "updated_at", "last_reading_at", "state","geohash", "uuid", "kit_id"]
    end
  end

  def self.ransackable_associations(auth_object = nil)
    [
      "components", "devices_tags", "owner",
      "pg_search_document" , "postprocessing", "sensors",
       "tags", "forwarding_destination"
    ]
  end

  def sensor_keys
    sensor_map.keys
  end

  def sensor_map
    components.map { |c| [c.key, c.sensor.id]}.to_h
  end

  def create_or_find_component_by_sensor_id(sensor_id)
    return nil if sensor_id.nil? || !Sensor.exists?(id: sensor_id)
    components.create_or_find_by!(sensor_id: sensor_id)
  end

  def create_or_find_component_by_sensor_key(sensor_key)
    return nil if sensor_key.nil?
    sensor = Sensor.find_by(default_key: sensor_key)
    return nil if sensor.nil?
    components.create_or_find_by!(sensor_id: sensor.id)
  end

  def create_or_find_component_for_sensor_reading(reading)
    key_or_id = reading["id"]
    if key_or_id.is_a?(Integer) || key_or_id =~ /\d+/
      # It's an integer and therefore a sensor id
      create_or_find_component_by_sensor_id(key_or_id)
    else
      create_or_find_component_by_sensor_key(key_or_id)
    end
  end

  def find_component_by_sensor_id sensor_id
    components.where(sensor_id: sensor_id).first
  end

  def find_sensor_id_by_key sensor_key
    sensor_map[sensor_key.to_s] rescue nil
  end

  def find_sensor_key_by_id sensor_id
    sensor_map.invert[sensor_id] rescue nil
  end

  def user_tags
    tags.map(&:name)
  end

  def user_tags=(tag_names)
    self.tags = tag_names.split(",").map do |n|
      Tag.find_by!(name: n.strip)
    end
  end

  def owner_username
    owner.username if owner
  end

  def online?
    last_reading_at.present? and last_reading_at > 60.minutes.ago
  end

  def system_tags
    [
      exposure, # indoor / outdoor
      ('new' if created_at > 1.week.ago), # new
      ('test_device' if is_test?),
      ( online? ? 'online' : 'offline') # state
    ].reject(&:blank?).sort
  end

  def all_tags
    system_tags + user_tags
  end

  def to_s
    name
  end

  def archive
    update({mac_address: nil, old_mac_address: mac_address, archived_at: Time.now})
  end

  def unarchive
    updates = { archived_at: nil }
    unless Device.unscoped.where(mac_address: old_mac_address).exists?
      updates.merge!({mac_address: old_mac_address, old_mac_address: nil})
    end
    update(updates)
  end

  def firmware
    if firmware_version.present?
      "sck:#{firmware_version}"
    end
  end

  def status
    data.present? ? state : 'new'
  end

  def soft_state
    if data.present?
      'has_published'
    elsif mac_address.present? || device_token.present?
      'never_published'
    else
      'not_configured'
    end
  end

  # TODO Remove: Deprevated in API v1
  def formatted_location(slim = false)
    {
      exposure: exposure,
      elevation: slim ? nil : elevation.try(:to_i),
      latitude: latitude,
      longitude: longitude,
      geohash: slim ? nil : geohash,
      city: city,
      country_code: slim ? nil : country_code,
      country: country_name
    }.compact
  end

  def location_string
    [city, country_name].compact.join(", ")
  end

  # TODO Remove: Deprevated in API v1
  def formatted_data
    s = {
      sensors: []
    }

    components.sort_by {|c| c.sensor.name }.each do |component|
      sensor = component.sensor
      sa = sensor.attributes.except(*%w{key equation reverse_equation measurement_id})
      sa = sa.merge(
        measurement: sensor.measurement&.for_sensor_json,
        value: (data ? data["#{sensor.id}"] : nil),
        prev_value: (old_data ? old_data["#{sensor.id}"] : nil),
        last_reading_at: component.last_reading_at,
        tags: sensor.tags
      )
      s[:sensors] << sa
    end

    return s
  end

  def self.geocode_all_without_location
    Device.where(location: "{}").where.not(latitude: nil).each do |device|
      device.reverse_geocode
      device.save validate: false
      sleep(1)
    end
  end

  def remove_mac_address_for_newly_registered_device!
    update(old_mac_address: mac_address, mac_address: nil)
  end

  def update_component_timestamps(timestamp, sensor_ids)
    components.select {|c| sensor_ids.include?(c.sensor_id) }.each do |component|
      component.lock! if self.class.connection.transaction_open?
      if !component.reload.last_reading_at || timestamp > component.last_reading_at
        component.update_column(:last_reading_at, timestamp)
      end
    end
  end

  # TODO Remove: Deprevated in API v1
  def data_policy(authorized=false)
    {
      is_private: is_private,
      enable_forwarding: authorized ? enable_forwarding : "[FILTERED]",
      precise_location: authorized ? precise_location : "[FILTERED]",
      forwarding_destination: authorized ? forwarding_destination&.name : "[FILTERED]"
    }
  end

  # TODO Remove: Deprevated in API v1
  def hardware(authorized=false)
    {
      name: hardware_name,
      type: hardware_type,
      version: hardware_version,
      slug: hardware_slug,
      last_status_message: authorized ? hardware_info : "[FILTERED]",
    }
  end

  def hardware_name
    hardware_name_override || [hardware_version ? "SmartCitizen Kit" : "Unknown", hardware_version].compact.join(" ")
  end

  def hardware_type
    hardware_type_override || (hardware_version ? "SCK" : "Unknown")
  end

  def hardware_version
    hardware_version_override || hardware_info&.fetch('hw_ver', nil)
  end

  def hardware_slug
    hardware_slug_override || [hardware_type.downcase, hardware_version&.gsub(".", ",")].compact.join(":")
  end

  def forward_readings?
    enable_forwarding && owner.forward_device_readings?
  end

  def forwarding_token
    owner.forwarding_token
  end

  def truncate_and_fuzz_location!
    if latitude && longitude
      fuzz_decimal_places = 3
      total_decimal_places = 5
      lat_fuzz = self.precise_location ? 0.0 : (Random.rand * 1/10.0**fuzz_decimal_places)
      long_fuzz = self.precise_location ? 0.0 : (Random.rand * 1/10.0**fuzz_decimal_places)
      self.latitude = (self.latitude + lat_fuzz).truncate(total_decimal_places)
      self.longitude = (self.longitude + long_fuzz).truncate(total_decimal_places)
    end
  end

  def csv_export_requested_recently?
    !!self.csv_export_requested_at && self.csv_export_requested_at > 15.minutes.ago
  end

  def request_csv_archive_for!(user)
    return false if self.csv_export_requested_recently?
    self.update_column(:csv_export_requested_at, Time.now.utc)
    mailer = UserMailer.device_archive(self.id, user.id)
    mailer.deliver_later
    return true
  end

  private

app/controllers/ui/application_controller.rb
module Ui
  class ApplicationController < ActionController::Base
    layout "application"
    include SharedControllerMethods

    private

    def add_breadcrumbs(*crumbs)
      crumbs.each do |crumb|
        add_breadcrumb(*crumb)
      end
    end

    def add_breadcrumb(label, url=nil)
      breadcrumbs << Breadcrumb.new(breadcrumbs, label, url)
    end

    def breadcrumbs
      @breadcrumbs ||= []
    end

    def goto_or(url)
      params[:goto].present? ? params[:goto] : url
    end

    helper_method :breadcrumbs
  end
end

app/controllers/ui/sessions_controller.rb
module Ui
  class SessionsController < ApplicationController
    include SharedControllerMethods
    require 'uri'
    require 'net/http'
    require 'net/https'

    def new
      @title = I18n.t(:new_session_title)
      redirect_to ui_users_url if current_user
    end

    def index
      redirect_to new_ui_session_path
    end

    def create
      if params[:send_password_email]
        reset_password_email
        redirect_to new_ui_session_path
        return
      end

      user = User.where("lower(email) = lower(?) OR lower(username) = lower(?)",
                        params[:username_or_email], params[:username_or_email]).first
      if user && user.authenticate_with_legacy_support(params[:password])
        session[:user_id] = user.id

        if params[:goto].include? 'discourse'
          redirect_to session[:discourse_url]
        else
          flash[:success] = I18n.t(:new_session_success)
          redirect_to goto_or(session[:user_return_to] || ui_users_path)
        end
      else
        flash.now.alert = I18n.t(:new_session_failure)
        render "new"
      end
    end

    def reset_password_email
      user = User.where("lower(email) = lower(?) OR lower(username) = lower(?)",
                        params[:username_or_email], params[:username_or_email]).first

      if user
        authorize user, :request_password_reset?
        user.send_password_reset
      end
      flash[:notice] = I18n.t(:password_reset_notice)
    end

    def password_reset_landing
      @title = I18n.t(:password_reset_landing_title)
      @token = params[:token]
    end

    def change_password
      @token = params.require(:token)

      if params.require(:password) != params.require(:password_confirmation)
        flash[:alert] = I18n.t(:password_reset_failure)
        render "password_reset_landing"
        return
      end

      @user = User.find_by(password_reset_token: @token)
      if @user
        authorize @user, :update_password?
        @user.update(params.permit(:password, :password_confirmation).merge(password_reset_token: nil))
        flash[:success] = I18n.t(:password_reset_success, username: @user.username)
        redirect_to new_ui_session_path
      else
        flash[:alert] = I18n.t(:password_reset_invalid)
        render "password_reset_landing"
      end
    end

    def destroy
      session[:user_id] = nil
      redirect_to goto_or(login_url), notice: I18n.t(:destroy_session_success)
    end
  end
end

app/controllers/ui/static_controller.rb
module Ui
  class StaticController < ApplicationController
    def policy
    end
  end
end

app/views/ui/devices/_actions.html.erb
<p class="mb-0">
<%= sc_nav_button_to(t(:show_device_on_map_cta), "#{map_base_url}#{device.id}", local_assigns.merge(external: true)) %>
  <% if authorize? device, :update? %>
    <%= sc_nav_button_to(t(:show_device_edit_cta, name: device.name), edit_ui_device_path(device, goto: request.path), local_assigns) %>
  <% end %>
  <% if authorize? device, :upload? %>
    <%= sc_nav_button_to(t(:show_device_upload_cta), upload_ui_device_path(device, goto: request.path), local_assigns) %>
  <% end %>
  <% if authorize? device, :download? %>
    <%= sc_nav_button_to(t(:show_device_download_cta), download_ui_device_path(device, goto: request.path), local_assigns) %>
  <% end %>
</p>

app/views/ui/devices/_device.html.erb
<div class="device listing row border-top g-0 z-0">
  <%= link_to(ui_device_path(device.id), class: "listing-link z-1") do %>
    <span class="sr-only"><%= device.name %></span>
  <% end %>
  <div class="col-12 col-md-3">
    <% if device.latitude && device.longitude %>
      <%= render partial: "ui/shared/map", locals: { points: [{lat: device.latitude, lng: device.longitude}] } %>
    <% end %>
  </div>
  <div class="col-12 col-md-9 p-3 pb-4 darker">
    <h3 class="mb-1 text-break"><%= device.name %></h3>
    <%= render partial: "ui/devices/meta", locals: { device: device, hide_owner: local_assigns[:hide_owner] } %>
    <% if local_assigns[:with_actions] %>
      <div class="mt-4 z-2 position-relative">
        <%= render partial: "ui/devices/actions", locals: { device: device } %>
      </div>
    <% end %>
  </div>
</div>

app/views/ui/devices/_fields.html.erb
<div class="mb-5">
  <h2 class="mb-4"><%= t(:device_form_details_subhead) %></h2>
  <%= form.text_field :name %>
  <%= form.text_field :description %>
  <%= form.select :exposure, options_for_select(Device::EXPOSURE_VALUES.map { |v| [v.capitalize, v]}, device.exposure) %>
</div>

<% if device.mac_address || local_assigns[:include_hardware_info] %>
  <div class="mb-5">
    <h2 class="mb-0"><%= t(:device_form_hardware_info_subhead) %></h2>
    <p class="mb-4"> <%= t(:device_form_hardware_info_blurb_html) %></p>
    <%= form.select :hardware_version_override,
      options_for_select(
        Device::HARDWARE_VERSION_OVERRIDE_VALUES.map { |v| [t(:"device_form_hardware_version_override_option_#{v.gsub(".", "_")}"), v]},
        device.hardware_version_override
      ),
      required: true, label: t(:device_form_hardware_version_override_label) %>
    <%= form.text_field :mac_address, required: true, label: t(:device_form_mac_address_label), pattern: "^([0-9A-Fa-f]{2}[:\\-]){5}([0-9A-Fa-f]{2})$", help: t(:device_form_mac_address_help) %>
  </div>
<% end %>

<div class="mb-5">
  <h2 class="mb-0" ><%= t(:device_form_location_subhead) %></h2>
  <p class="mb-4"> <%= t(:device_form_location_blurb) %></p>
  <%= form.hidden_field :latitude %>
  <%= form.hidden_field :longitude %>
  <%= render partial: "ui/shared/map_location_picker", locals: { latitude_input_id: "device_latitude", longitude_input_id: "device_longitude"} %>
</div>
<div class="mb-5">
  <h2 class="mb-0"><%= t(:device_form_tags_subhead) %></h2>
  <p class="mb-4"> <%= t(:device_form_tags_blurb) %></p>
  <%= form.select :tag_ids, options_from_collection_for_select(Tag.all, :id, :name, { selected: device.tag_ids }), { label: t(:device_form_tags_label)},  { multiple: true, class: "tag-select" } %>
</div>
<div class="mb-5">
  <h2 class="mb-0"><%= t(:device_form_privacy_subhead) %></h2>
  <p class="mb-4"> <%= t(:device_form_privacy_blurb) %></p>
  <%= form.check_box :is_private, label: t(:device_form_is_private_label) %>
  <%= form.check_box :precise_location, label: t(:device_form_precise_location_label) %>
</div>
<div class="mb-5">
  <h2 class="mb-0"><%= t(:device_form_notifications_subhead) %></h2>
  <p class="mb-4"> <%= t(:device_form_notifications_blurb) %></p>
  <%= form.check_box :notify_low_battery, label: t(:device_form_notify_low_battery_label) %>
  <%= form.check_box :notify_stopped_publishing, label: t(:device_form_notify_stopped_publishing_label) %>
</div>
<% if current_user.is_admin_or_researcher? %>
  <div>
    <h2 class="mb-4"><%= t(:device_form_researcher_options_subhead) %></h2>
    <% if device.owner.forward_device_readings? %>
      <%= form.check_box :enable_forwarding, label: t(:device_form_enable_forwarding_label) %>
      <%= form.select :forwarding_destination_id, options_for_select(
        ForwardingDestination.all.map { |fd| [fd.name, fd.id] },
        device.forwarding_destination_id
      ), label: t(:device_form_forwarding_destination_label), include_blank: "Default" %>
    <% end %>
    <%= form.fields_for :postprocessing, device.postprocessing || Postprocessing.new do |fp| %>
      <%= fp.text_field :hardware_url, label: t(:device_form_hardware_url_label), help: t(:device_form_postprocessing_blurb_html) %>
    <% end %>
  </div>
<% end %>

app/views/ui/devices/_meta.html.erb
<% show_description = device.description.present? && !local_assigns[:hide_description] %>

<p class="mb-0 device-status <%= device.online? ? "online" : "offline" %>">
  <span class="pe-1"><%= show_svg("status_icon.svg") %></span>
  <strong><%= device.hardware_name %> (<%= device.online? ? t(:device_meta_online_adjective) : t(:device_meta_offline_adjective) %>)</strong>
</p>
<% unless local_assigns[:hide_owner] %>
  <p class="mb-0">
  <span class="pe-1"><%= show_svg("user_details_icon_light.svg") %></span>
    <%= link_to(device.owner.username, ui_user_path(device.owner.username), class: "d-inline-block position-relative subtle-link z-3") %>
  </p>
<% end %>
<p class="mb-0">
  <span class="pe-1"><%= show_svg("location_icon.svg") %></span>
  <%= device.location_string %>
</p>
<% unless local_assigns[:hide_last_reading_at] %>
  <p class="mb-0">
    <span class="pe-1"><%= show_svg("clock-fill.svg") %></span>
    <% if device.last_reading_at %>
      <%= t :device_meta_last_reading_at, time: time_ago_in_words(local_time_zone.at(device.last_reading_at)) %>
    <% else %>
      <%= t :device_meta_no_readings_message %>
    <% end %>
  </p>
<% end %>

app/views/ui/devices/_profile_header.html.erb
<% content_for :profile_header_image do %>
  <div class="circular-image-crop image-border">
    <%= render partial: "ui/shared/map", locals: { points: [{lat: device.latitude, lng: device.longitude}] } %>
  </div>
<% end %>
<% content_for :profile_header_meta do %>
  <%= render partial: "ui/devices/meta", locals: { device: device,  hide_last_reading_at: true } %>
<% end %>
<% content_for :profile_header_actions do %>
  <%= render partial: "ui/devices/actions", locals: { device: device, dark_buttons: true } %>
<% end %>
<%= render partial: "ui/shared/profile_header", locals: { title: t(:show_device_headline, name: device.name), title_link: ui_device_path(device.id) } %>

app/views/ui/devices/delete.html.erb
<%= render partial: "ui/devices/profile_header", locals: { device: @device } %>
<%= render layout: "ui/shared/form_container", locals: { title: t(:delete_device_header) } do %>
  <%= bootstrap_form_tag url: ui_device_path(@device.id), method: :delete do |f| %>
    <p><%= t(:delete_device_warning_html, name: @device.name) %></p>
    <%= f.text_field :name, label: t(:delete_device_name_label)  %>
    <div class="mt-4">
      <%= f.primary t(:delete_device_submit), class: "btn btn-danger w-100 w-md-auto" %>
    </div>
  <% end %>
<% end %>

app/views/ui/devices/edit.html.erb
<%= render partial: "ui/devices/profile_header", locals: { device: @device } %>
<%= render layout: "ui/shared/form_container", locals: { title: t(:edit_device_header) } do %>
  <%= bootstrap_form_for @device, url: ui_device_path(@device) do |form| %>
    <%= hidden_field_tag :goto, params[:goto] %>
    <%= render partial: "fields", locals: { device: @device, form: form } %>
    <%= render partial: "ui/shared/form_buttons", locals: { form: form, back_href: ui_device_path(@device.id), submit_label: t(:edit_device_submit) } %>
  <% end %>
  <% if authorize? @device, :destroy? %>
    <%= render layout: "ui/shared/danger_zone" do %>
      <div><%= link_to t(:edit_device_delete_device_submit), delete_ui_device_path(@device.id), class: "btn btn-danger w-100 w-md-25 justify-content-center" %></div>
    <% end %>
  <%  end %>
<%  end %>

app/views/ui/devices/new.html.erb
<%= render partial: "ui/users/header", locals: { user:  current_user } %>
<%= render layout: "ui/shared/form_container" do %>
  <%= bootstrap_form_for @device, url: ui_devices_path do |form| %>
    <%= render partial: "fields", locals: { device: @device, form: form, include_hardware_info: true } %>
    <%= render partial: "ui/shared/form_buttons", locals: { form: form, back_href: register_ui_devices_path, submit_label: t(:new_device_submit) } %>
  <% end %>
<% end %>

app/views/ui/devices/onboarding.html.erb
<%= render partial: "ui/users/header", locals: { user:  current_user } %>
<%= render layout: "ui/shared/container" do %>
  <%= render layout: "ui/shared/box", locals: { no_padding: true, class: "mb-5 onboarding" }  do %>
    <div class="p-3">
      <h2>Device Onboarding</h2>
    </div>
    <%= bootstrap_form_for :devices, url: onboarding_ui_devices_path do |form| %>
      <div class="border-bottom border-2">
        <div class="devices">
          <% if @devices %>
            <%= render partial: "ui/devices/onboarding_device", collection: @devices, locals: { form: form } %>
          <% else %>
            <%= render partial: "ui/devices/onboarding_device", locals: { form: form } %>
          <% end %>
        </div>
        <template class="device-template">
          <%= render partial: "ui/devices/onboarding_device", locals: { form: form } %>
        </template>
      </div>
      <div class="row px-3 g-3">
        <div class="col-6 col-md-3 offset-md-6 py-3 add-device-button">
          <a class="btn btn-secondary w-100" href="#">
            Add more
          </a>
        </div>
        <div class="col-6 col-md-3 py-3">
          <%= form.primary "Submit", class: "btn btn-primary w-100 justify-content-center" %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>