config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == ENV["sidekiq_username"] && password == ENV["sidekiq_password"]
    end
  end
  mount Sidekiq::Web, at: "/sidekiq"

  get "discourse/sso" => 'discourse#sso'

  get "login", to: redirect("/ui/sessions/new")
  get "logout", to: redirect("/ui/sessions/destroy")
  get "password_reset/:token", to: redirect("/ui/password_reset/%{token}")

  namespace "ui" do
    get "/", to: redirect("/ui/users")

    get "/policy", to: "static#policy"

    constraints id: /[^\/]+/ do
      # Explicitly override to allow usernames with dots.
      # See:https://stackoverflow.com/questions/5369654/why-do-routes-with-a-dot-in-a-parameter-fail-to-match
      resources :users, as: "users" do
        member do
          get :delete
          get :edit
          get :secrets
        end
        collection do
          get :post_delete
        end
      end
    end

    resources :devices, as: "devices" do
      member do
        get :edit
        get :delete
        get :download
        get :upload
        post :upload, to: "devices#upload_readings"
        post :download, to: "devices#download_confirm"
      end
      collection do
        get :register
        get :new
        post :create
        get :onboarding
        post :onboarding, to: "devices#onboarding_create"
      end
    end

    resources :experiments, as: "experiments" do
      member do
        get :readings
        get :delete
      end
    end

    get "sessions/destroy", to: "sessions#destroy"
    resources :sessions, as: "sessions"
    post 'change_password', to: 'sessions#change_password', as: 'change_password'
    get 'password_reset/:token', to: 'sessions#password_reset_landing', as: 'password_reset'
  end

  api_version(module: "V1", path: { value: "v1" }, header: {name: "Accept", value: "application/vnd.smartcitizen; version=1"}, defaults: { format: :json }) do
    resources :devices
  end

  api_version(module: "V0", path: {value: "v0"}, header: {name: "Accept", value: "application/vnd.smartcitizen; version=0"}, default: true, defaults: { format: :json }) do
    # devices
    resources :devices do
      member do
        resources :readings, only: [:index, :create] do
          get 'csv_archive', on: :collection
        end
      end
      get 'world_map', on: :collection
      get 'fresh_world_map', on: :collection
    end
    # readings
    match "add" => "readings#legacy_create", via: [:get, :post, :patch, :put]
    match "datetime" => "readings#datetime", via: [:get, :post, :patch, :put]

    resources :sensors, except: [:destroy]
    resources :components, only: [:show, :index]
    resources :sessions, only: :create
    resources :experiments

    resources :tag_sensors
    resources :tags
    resources :measurements

    constraints id: /[^\/]+/ do
      # Explicitly override to allow usernames with dots.
      # See:https://stackoverflow.com/questions/5369654/why-do-routes-with-a-dot-in-a-parameter-fail-to-match
      resources :users
    end
    resources :password_resets, only: [:show, :create, :update]
    resources :oauth_applications, path: 'applications'
    get :forward, to: "forwarding#authorize"

    resources :me, only: [:index] do
      patch '/' => 'me#update', on: :collection
      put '/' => 'me#update', on: :collection
      delete '/' => 'me#destroy', on: :collection
    end

    # onboarding process
    namespace :onboarding do
      get 'device', to: 'orphan_devices#show'
      post 'device', to: 'orphan_devices#create'
      patch 'device', to: 'orphan_devices#update'
      post 'user', to: 'device_registrations#find_user'
      post 'register', to: 'device_registrations#register_device'
    end

    get "discourse/sso" => 'discourse#sso'
    get 'search' => 'static#search'
    get 'metrics' => 'static#metrics'
    # use_doorkeeper
    # root to: 'static#home'
    get '/', to: 'static#home'
    get '/version', to: "static#version"
    get "/404" => "errors#not_found"
    get "/500" => "errors#exception"
    get "/test_error" => "errors#test_error"

    # Active Storage cannot show the correct url if using catchall matchers
    # https://github.com/rails/rails/issues/31228
    # Disable until a solution is found
    #match "*path", to: "errors#not_found", via: :all
  end

  # get '*path', :to => redirect("/v0/%{path}")
  # root to: redirect('/v0')

end

app/controllers/ui/application_controller.rb
module Ui
  class ApplicationController < ActionController::Base
    layout "application"
    include SharedControllerMethods

    private

    def add_breadcrumbs(*crumbs)
      crumbs.each do |crumb|
        add_breadcrumb(*crumb)
      end
    end

    def add_breadcrumb(label, url=nil)
      breadcrumbs << Breadcrumb.new(breadcrumbs, label, url)
    end

    def breadcrumbs
      @breadcrumbs ||= []
    end

    def goto_or(url)
      params[:goto].present? ? params[:goto] : url
    end

    helper_method :breadcrumbs
  end
end

app/controllers/ui/devices_controller.rb
module Ui
  class DevicesController < ApplicationController
    def show
      find_device!
      return unless authorize_device! :show?, :show_device_forbidden
      @title = I18n.t(:show_device_title, name: @device.name)
      add_breadcrumbs(
        [I18n.t(:show_user_title, owner: owner_name), ui_user_path(@device.owner.username)],
        [@title, ui_device_path(@device.id)]
      )
    end

    def edit
      find_device!
      return unless authorize_device! :update?, :edit_device_forbidden
      @title = I18n.t(:edit_device_title, name: @device.name)
      add_breadcrumbs(
        [I18n.t(:show_user_title, owner: owner_name), ui_user_path(@device.owner.username)],
        [I18n.t(:show_device_title, name: @device.name), ui_device_path(@device.id)],
        [I18n.t(:edit_breadcrumb), edit_ui_device_path(@device.id)]
      )
    end

    def update
      find_device!
      return unless authorize_device! :update?, :edit_device_forbidden
      if @device.update(device_params)
        flash[:success] = I18n.t(:update_device_success)
        redirect_to goto_or(ui_device_path(@device.id))
      else
        flash[:alert] = I18n.t(:update_device_failure)
        render :edit, status: :unprocessable_entity
      end
    end

    def delete
      find_device!
      return unless authorize_device! :destroy?, :delete_device_forbidden
      @title = I18n.t(:delete_device_title, name: @device.name)
      add_breadcrumbs(
        [I18n.t(:show_user_title, owner: owner_name), ui_user_path(@device.owner.username)],
        [I18n.t(:show_device_title, name: @device.name), ui_device_path(@device.id)],
        [I18n.t(:edit_breadcrumb, name: @device.name), edit_ui_device_path(@device.id)],
        [I18n.t(:delete_breadcrumb, name: @device.name), delete_ui_device_path(@device.id)]
      )
    end

    def destroy
      find_device!
      return unless authorize_device! :destroy?, :delete_device_forbidden
      if @device.name != params[:name]
        flash[:alert] = I18n.t(:delete_device_wrong_name)
        redirect_to delete_ui_device_path(@device.id)
        return
      end
      @device.archive!
      flash[:success] = I18n.t(:delete_device_success)
      redirect_to ui_user_path(current_user.username)
    end

    def download
      find_device!
      return unless authorize_device! :download?, :download_device_forbidden
      @title = I18n.t(:download_device_title, name: @device.name)
      add_breadcrumbs(
        [I18n.t(:show_user_title, owner: owner_name), ui_user_path(@device.owner.username)],
        [I18n.t(:show_device_title, name: @device.name), ui_device_path(@device.id)],
        [I18n.t(:download_breadcrumb), download_ui_device_path(@device.id)]
      )
    end

    def download_confirm
      find_device!
      return unless authorize_device! :download?, :download_device_forbidden
      if @device.request_csv_archive_for!(current_user)
        flash[:success] = I18n.t(:download_device_success)
      else
        flash[:alert] = I18n.t(:download_device_requested_too_soon)
      end
      redirect_to goto_or(ui_device_path(@device.id))
    end

    def register
      unless current_user
        flash[:alert] = I18n.t(:register_device_forbidden)
        redirect_to login_path
        return
      end
      @title = I18n.t(:register_device_title)
      add_breadcrumbs(
        [I18n.t(:show_user_title, owner: owner_name), ui_user_path(current_user)],
        [@title, register_ui_devices_path]
      )
    end

    def new
      unless current_user
        flash[:alert] = I18n.t(:register_device_forbidden)
        redirect_to login_path
        return
      end
      @title = I18n.t(:new_device_title)
      add_breadcrumbs(
        [I18n.t(:show_user_title, owner: owner_name), ui_user_path(current_user)],
        [I18n.t(:register_device_title), register_ui_devices_path],
        [I18n.t(:legacy_breadcrumb), new_ui_device_path]
      )
      @device = Device.new(owner: current_user)
    end

    def onboarding
      unless current_user
        flash[:alert] = I18n.t(:register_device_forbidden)
        redirect_to login_path
        return
      end
      @title = I18n.t(:new_device_title)
      add_breadcrumbs(
        [I18n.t(:show_user_title, owner: owner_name), ui_user_path(current_user)],
        [I18n.t(:register_device_title), register_ui_devices_path],
        [I18n.t(:legacy_breadcrumb), new_ui_device_path]
      )
    end

    def create
      unless current_user
        flash[:alert] = I18n.t(:register_device_forbidden)
        redirect_to login_path
        return
      end
      @device = new_device(device_params)
      if @device.valid?
        @device.save
        flash[:success] = I18n.t(:new_device_success)
        redirect_to ui_device_path(@device.id)
      else
        flash[:alert] = I18n.t(:new_device_failure)
        render :new, status: :unprocessable_entity
      end
    end

    def onboarding_create
      unless current_user
        flash[:alert] = I18n.t(:register_device_forbidden)
        redirect_to login_path
        return
      end
      @devices = devices_params[:device].map do |attrs|
        new_device(attrs)
      end
      if @devices.all?(&:valid?)
        @devices.each(&:save)
        flash[:success] = I18n.t(:new_device_success)
        redirect_to ui_user_path(current_user)
      else
        flash[:alert] = I18n.t(:new_device_failure)
        render :onboarding, status: :unprocessable_entity
      end

    end

    def upload
      find_device!
      return unless authorize_device! :upload?, :upload_device_forbidden
      @title = I18n.t(:upload_device_title, name: @device.name)
      add_breadcrumbs(
        [I18n.t(:show_user_title, owner: owner_name), ui_user_path(@device.owner.username)],
        [I18n.t(:show_device_title, name: @device.name), ui_device_path(@device.id)],
        [I18n.t(:upload_breadcrumb), download_ui_device_path(@device.id)]
      )
    end

    def upload_readings
      find_device!
      return unless authorize_device! :upload?, :upload_device_forbidden
      params[:data_files].each do |file|
        CSVUploadJob.perform_later(@device.id, file.read)
      end
      flash[:success] = I18n.t(:upload_device_success)
      redirect_to goto_or(ui_device_path(@device.id))

    end


    private

    def new_device(attrs)
      device = Device.new(attrs)
      device.owner = current_user
      device
    end

    def devices_params
      params.require(:devices).permit(
        device: device_param_names
      )
    end

    def device_params
      params.require(:device).permit(
        *device_param_names
      )
    end

    def device_param_names
      [
        :name,
        :description,
        :exposure,
        :latitude,
        :longitude,
        :is_private,
        :precise_location,
        :enable_forwarding,
        :notify_low_battery,
        :notify_stopped_publishing,
        :hardware_version_override,
        :mac_address,
        :device_token,
        :forwarding_destination_id,
        { :tag_ids => [] },
        { :postprocessing_attributes => :hardware_url },
      ]
    end

    def find_device!
      @device = Device.find(params[:id])
    end

    def authorize_device!(action, alert)
      return true if authorize? @device, action
      flash[:alert] = I18n.t(alert)
      redirect_to current_user ? ui_user_path(current_user.username) : login_path
      return false
    end

    def owner_name(capitalize=true)
      owner = @device&.owner || current_user
      helpers.possessive(owner, current_user, capitalize: capitalize, third_person: true)
    end
  end
end

app/controllers/ui/sessions_controller.rb
module Ui
  class SessionsController < ApplicationController
    include SharedControllerMethods
    require 'uri'
    require 'net/http'
    require 'net/https'

    def new
      @title = I18n.t(:new_session_title)
      redirect_to ui_users_url if current_user
    end

    def index
      redirect_to new_ui_session_path
    end

    def create
      if params[:send_password_email]
        reset_password_email
        redirect_to new_ui_session_path
        return
      end

      user = User.where("lower(email) = lower(?) OR lower(username) = lower(?)",
                        params[:username_or_email], params[:username_or_email]).first
      if user && user.authenticate_with_legacy_support(params[:password])
        session[:user_id] = user.id

        if params[:goto].include? 'discourse'
          redirect_to session[:discourse_url]
        else
          flash[:success] = I18n.t(:new_session_success)
          redirect_to goto_or(session[:user_return_to] || ui_users_path)
        end
      else
        flash.now.alert = I18n.t(:new_session_failure)
        render "new"
      end
    end

    def reset_password_email
      user = User.where("lower(email) = lower(?) OR lower(username) = lower(?)",
                        params[:username_or_email], params[:username_or_email]).first

      if user
        authorize user, :request_password_reset?
        user.send_password_reset
      end
      flash[:notice] = I18n.t(:password_reset_notice)
    end

    def password_reset_landing
      @title = I18n.t(:password_reset_landing_title)
      @token = params[:token]
    end

    def change_password
      @token = params.require(:token)

      if params.require(:password) != params.require(:password_confirmation)
        flash[:alert] = I18n.t(:password_reset_failure)
        render "password_reset_landing"
        return
      end

      @user = User.find_by(password_reset_token: @token)
      if @user
        authorize @user, :update_password?
        @user.update(params.permit(:password, :password_confirmation).merge(password_reset_token: nil))
        flash[:success] = I18n.t(:password_reset_success, username: @user.username)
        redirect_to new_ui_session_path
      else
        flash[:alert] = I18n.t(:password_reset_invalid)
        render "password_reset_landing"
      end
    end

    def destroy
      session[:user_id] = nil
      redirect_to goto_or(login_url), notice: I18n.t(:destroy_session_success)
    end
  end
end

app/controllers/ui/static_controller.rb
module Ui
  class StaticController < ApplicationController
    def policy
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
  def profile_picture_url(user)
    if user.profile_picture.attached?
      polymorphic_url(user.profile_picture, only_path: false)
    else
      ''
    end
  end

  def possessive(user, current_user, params={})
    third_person = params[:third_person]
    first_person = params[:first_person]
    capitalize = params[:capitalize]
    if !third_person && current_user && current_user == user
      pronoun = t(first_person ? :first_person_possessive : :second_person_possessive)
      capitalize ? pronoun.capitalize : pronoun
    else
      t :third_person_possessive, username: user.username
    end
  end
end

app/views/ui/users/_actions.html.erb
<p class="mb-0">
  <% if authorize? user, :update? %>
    <%= sc_nav_button_to(t(:show_user_edit_cta, owner: possessive(user, current_user)), edit_ui_user_path(user), local_assigns) %>
  <% end %>
  <% if authorize? user, :show_secrets? %>
    <%= sc_nav_button_to(t(:show_user_secrets_cta, owner: possessive(user, current_user)), secrets_ui_user_path(user), local_assigns) %>
  <% end %>
  <% if authorize? user, :register_device? %>
    <%= sc_nav_button_to(t(:show_user_register_cta), register_ui_devices_path, local_assigns) %>
  <% end %>
  <% if authorize? user, :create_experiment? %>
    <%= sc_nav_button_to(t(:show_user_new_experiment_cta), new_ui_experiment_path, local_assigns) %>
  <% end %>
  <% if current_user == user %>
    <%= sc_nav_button_to(t(:show_user_log_out_cta), logout_path, local_assigns.merge(class: "hover-danger")) %>
  <% end %>
</p>

app/views/ui/users/_devices_collection.html.erb
<%= render layout: "ui/shared/box", locals: { no_padding: true, class: "mb-5" } do %>
  <div class="scroll-offset" id="devices"></div>
  <div class="p-3">
    <% if current_user == user && devices.length < 1 %>
      <%= render partial: "no_device_cta" %>
    <% else %>
      <h2><%= t :show_user_devices_heading %></h2>
      <% if devices.length < 1 %>
        <p><%= t :show_user_no_devices_message, username: user.username %></p>
      <% end %>
    <% end %>
  </div>
  <div class="<%= devices.total_pages > 1 ? "border-bottom": "" %>">
  <%=
    render partial: "ui/devices/device",
      collection: devices,
      locals: { hide_owner: true, with_actions: true }
    %>
  </div>
  <% if devices.total_pages > 1 %>
    <div class="w-100 mt-3 pagination-container">
      <div class="mx-auto width-fit-content">
        <%= paginate devices, param_name: :device_page, theme: "bootstrap-5" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/ui/users/_experiments_collection.html.erb
<%= render layout: "ui/shared/box", locals: { no_padding: true, class: "mt-3", inner_class: "drop-shadow-teal" } do %>
  <div class="scroll-offset" id="experiments"></div>
  <div class="p-3">
    <% if current_user == user && experiments.length < 1 %>
      <%= render partial: "no_experiment_cta" %>
    <% else %>
      <h2><%= t :show_user_experiments_heading %></h2>
      <% if experiments.length < 1 %>
        <p><%= t :show_user_no_experiments_message, username: user.username %></p>
      <% end %>
    <% end %>
  </div>
  <div class="<%= experiments.total_pages > 1 ? "border-bottom" : "" %>">
    <%=
      render partial: "ui/experiments/experiment",
        collection: experiments,
        locals: { hide_owner: true, with_actions: true }
      %>
  </div>
  <% if experiments.total_pages > 1 %>
    <div class="w-100 mt-3 experiments pagination-container">
      <div class="mx-auto width-fit-content">
        <%= paginate experiments, param_name: :experiment_page, theme: "bootstrap-5" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/ui/users/_header.html.erb
<% content_for :profile_header_image do %>
  <%= render partial: "ui/users/profile_image", locals: { user: user }  %>
<% end %>
<% content_for :profile_header_meta do %>
  <%= render partial: "ui/users/meta",  locals: { user: user } %>
<% end %>
<% content_for :profile_header_actions do %>
  <%= render partial: "ui/users/actions", locals: { user: user, dark_buttons: true } %>
<% end %>
<%= render partial: "ui/shared/profile_header", locals: { title: t(:show_user_headline, username: user.username), title_link: ui_user_path(user.username) } %>

app/views/ui/users/_meta.html.erb
<% if user.city || user.country %>
  <p class="mb-0">
    <span class="pe-1"><%= show_svg("location_icon.svg") %></span>
    <%= [user.city, user.country].join(", ") %>
  </p>
<% end %>
<% if user.url %>
  <p class="mb-0">
    <%= image_tag("url_icon_light.svg", class: "pe-1") %>
    <%= link_to(user.url, user.url, class: "link-white") %>
  </p>
<% end %>
  <p class="mb-0 device-status <%= device_collection_status_class(user) %>">
    <span class="pe-1"><%= show_svg("status_icon.svg") %></span>
    <strong>
      <%= pluralize(user.devices.length, t(:user_meta_device_noun)) %>
      <% if user.devices.length > 0 %>
        (<%= user.online_device_count %> <%= t(:user_meta_online_adjective) %>)
      <% end %>
    </strong>
  </p>

app/views/ui/users/_no_device_cta.html.erb
<h2><%= t :no_device_cta_heading %></h2>
<p><%= t :no_device_cta_blurb %></p>
<div class="mx-auto w-lg-75 w-100 mb-2">
  <%= image_tag "smartcitizen-2-2-kit.gif", class: "w-100" %>
  <a class="btn btn-primary mb-2 w-100" href="<%= t :no_device_kit_link_url %>"><%= t :no_device_kit_link_text %></a>
  <a class="btn btn-secondary w-100" href="<%= t :no_device_onboarding_link_url %>"><%= t :no_device_onboarding_link_text %></a>
</div>

app/views/ui/users/_no_experiment_cta.html.erb
<h2><%= t :no_experiment_cta_heading %></h2>
<p><%= t :no_experiment_cta_blurb %></p>
<div class="mx-auto w-lg-75 w-100 mb-2 mt-4">
  <a class="btn btn-primary w-100" href="<%= new_ui_experiment_path %>"><%= t :no_experiment_link_text %></a>
</div>

app/views/ui/users/_page_nav.html.erb
<div class="w-100 gx-0">
  <%= render layout: "ui/shared/box", locals: { no_padding: true, class: "w-100 sticky-lg-top z-2 page-nav", no_shadow: true } do %>
    <a href="#devices" class="subtle-link d-block p-3"><%= t :show_user_devices_heading %></a>
    <a href="#experiments" class="subtle-link d-block p-3 border-top"><%= t :show_user_experiments_heading %></a>
  <% end %>
</div>

app/views/ui/users/_profile_image.html.erb
<div class="<%= ["circular-image-crop image-border", local_assigns[:class]].compact.join(" ") %>">
  <%= image_tag(
    user.profile_picture.present? ? user.profile_picture : "default_avatar.svg",
    alt: local_assigns[:alt] || t(:profile_image_alt, username: user.username),
    class: "w-100"
  ) %>
</div>

app/views/ui/users/delete.html.erb
<%= render partial: "ui/users/header", locals: { user:  @user } %>
<%= render layout: "ui/shared/form_container" do %>
  <%= bootstrap_form_tag url: ui_user_path(@user.id), method: :delete do |f| %>
    <p><%= t(:delete_user_warning_html, username: current_user.username) %></p>
    <%= f.text_field :username, label: t(:delete_user_username_label, owner: possessive(@user, current_user))  %>
    <div class="mt-4">
      <%= f.primary t(:delete_user_submit, owner: possessive(@user, current_user, first_person: true)), class: "btn btn-danger w-100 w-md-auto" %>
    </div>
  <% end %>
<% end %>

app/views/ui/users/new.html.erb
<%= render layout: "ui/shared/form_container" do %>
  <%= bootstrap_form_for @user, url: ui_users_path do |f| %>
    <%= hidden_field_tag :goto, params[:goto] %>
    <%= f.hidden_field :preferred_time_zone, value: "Etc/UTC", class: "auto_fill_time_zone" %>
    <%= f.text_field :email %>
    <%= f.text_field :username %>
    <%= f.password_field :password %>
    <%= f.password_field :password_confirmation %>
    <div class="mt-4">
      <%= f.check_box :ts_and_cs, label: t(:new_user_ts_and_cs_label_html) %>
    </div>
    <%= render partial: "ui/shared/form_buttons", locals: {form: f, back_href: new_ui_session_path, back_label: t(:new_user_login_link), submit_label: t(:new_user_submit) } %>
  <% end %>
<% end %>

app/views/ui/users/post_delete.html.erb
<%= render layout: "ui/shared/form_container" do %>
  <p><%= t(:post_delete_user_blurb_html)%></p>
  <div class="mt-4">
    <a href="<%= t(:post_delete_user_cta_link) %>" class="btn btn-primary w-100 w-md-auto"><%= t(:post_delete_user_cta) %></a>
  </div>
<% end %>

app/views/ui/users/secrets.html.erb
<%= render partial: "ui/users/header", locals: { user:  @user } %>
<%= render layout: "ui/shared/form_container" do %>
  <p><%= t :secrets_user_blurb_html %></p>
  <%= render partial: "ui/shared/copyable_input", locals: {
    name: t(:secrets_user_api_key_label),
    value: @user.access_token.token,
    id: "api-key"
  } %>

  <% if @user.forward_device_readings? %>
    <div class="mt-5">
      <h1 class="mb-4"><%= t :secrets_user_forwarding_heading, owner: possessive(@user, current_user) %></h1>
      <p><%= t :secrets_user_forwarding_blurb_html %></p>
      <%= render partial: "ui/shared/copyable_input", locals: {
        name: t(:secrets_user_forwarding_token_label),
        value: @user.forwarding_token,
        id: "forwarding-token"
      } %>
    <%= render partial: "ui/shared/copyable_input", locals: {
      name: t(:secrets_user_forwarding_username_label),
      value: @user.forwarding_username,
      id: "forwarding-username"
    } %>
    </div>
  <% end %>
<% end %>

app/views/ui/users/show.html.erb
<%= render partial: "ui/users/header", locals: { user:  @user } %>
<% content_for :two_column_sidebar do %>
  <%= render partial: "ui/users/page_nav" %>
<% end %>
<% content_for :two_column_main do %>

  <%= render partial: "ui/users/devices_collection", locals: { user: @user, devices: @devices } %>
  <%= render partial: "ui/users/experiments_collection", locals: { user: @user, experiments: @experiments } %>
<% end %>
<%= render partial: "ui/shared/two_column" %>