config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == ENV["sidekiq_username"] && password == ENV["sidekiq_password"]
    end
  end
  mount Sidekiq::Web, at: "/sidekiq"

  get "discourse/sso" => 'discourse#sso'

  get "login", to: redirect("/ui/sessions/new")
  get "logout", to: redirect("/ui/sessions/destroy")
  get "password_reset/:token", to: redirect("/ui/password_reset/%{token}")

  namespace "ui" do
    get "/", to: redirect("/ui/users")

    get "/policy", to: "static#policy"

    constraints id: /[^\/]+/ do
      # Explicitly override to allow usernames with dots.
      # See:https://stackoverflow.com/questions/5369654/why-do-routes-with-a-dot-in-a-parameter-fail-to-match
      resources :users, as: "users" do
        member do
          get :delete
          get :edit
          get :secrets
        end
        collection do
          get :post_delete
        end
      end
    end

    resources :devices, as: "devices" do
      member do
        get :edit
        get :delete
        get :download
        get :upload
        post :upload, to: "devices#upload_readings"
        post :download, to: "devices#download_confirm"
      end
      collection do
        get :register
        get :new
        post :create
        get :onboarding
        post :onboarding, to: "devices#onboarding_create"
      end
    end

    resources :experiments, as: "experiments" do
      member do
        get :readings
        get :delete
      end
    end

    get "sessions/destroy", to: "sessions#destroy"
    resources :sessions, as: "sessions"
    post 'change_password', to: 'sessions#change_password', as: 'change_password'
    get 'password_reset/:token', to: 'sessions#password_reset_landing', as: 'password_reset'
  end

  api_version(module: "V1", path: { value: "v1" }, header: {name: "Accept", value: "application/vnd.smartcitizen; version=1"}, defaults: { format: :json }) do
    resources :devices
  end

  api_version(module: "V0", path: {value: "v0"}, header: {name: "Accept", value: "application/vnd.smartcitizen; version=0"}, default: true, defaults: { format: :json }) do
    # devices
    resources :devices do
      member do
        resources :readings, only: [:index, :create] do
          get 'csv_archive', on: :collection
        end
      end
      get 'world_map', on: :collection
      get 'fresh_world_map', on: :collection
    end
    # readings
    match "add" => "readings#legacy_create", via: [:get, :post, :patch, :put]
    match "datetime" => "readings#datetime", via: [:get, :post, :patch, :put]

    resources :sensors, except: [:destroy]
    resources :components, only: [:show, :index]
    resources :sessions, only: :create
    resources :experiments

    resources :tag_sensors
    resources :tags
    resources :measurements

    constraints id: /[^\/]+/ do
      # Explicitly override to allow usernames with dots.
      # See:https://stackoverflow.com/questions/5369654/why-do-routes-with-a-dot-in-a-parameter-fail-to-match
      resources :users
    end
    resources :password_resets, only: [:show, :create, :update]
    resources :oauth_applications, path: 'applications'
    get :forward, to: "forwarding#authorize"

    resources :me, only: [:index] do
      patch '/' => 'me#update', on: :collection
      put '/' => 'me#update', on: :collection
      delete '/' => 'me#destroy', on: :collection
    end

    # onboarding process
    namespace :onboarding do
      get 'device', to: 'orphan_devices#show'
      post 'device', to: 'orphan_devices#create'
      patch 'device', to: 'orphan_devices#update'
      post 'user', to: 'device_registrations#find_user'
      post 'register', to: 'device_registrations#register_device'
    end

    get "discourse/sso" => 'discourse#sso'
    get 'search' => 'static#search'
    get 'metrics' => 'static#metrics'
    # use_doorkeeper
    # root to: 'static#home'
    get '/', to: 'static#home'
    get '/version', to: "static#version"
    get "/404" => "errors#not_found"
    get "/500" => "errors#exception"
    get "/test_error" => "errors#test_error"

    # Active Storage cannot show the correct url if using catchall matchers
    # https://github.com/rails/rails/issues/31228
    # Disable until a solution is found
    #match "*path", to: "errors#not_found", via: :all
  end

  # get '*path', :to => redirect("/v0/%{path}")
  # root to: redirect('/v0')

end

app/models/experiment.rb
require_relative "validators/datetime_validator"

class Experiment < ApplicationRecord
  belongs_to :owner, class_name: "User"
  has_and_belongs_to_many :devices

  validates_presence_of :name, :owner
  validates_inclusion_of :is_test, in: [true, false]
  validates :starts_at_before_type_cast, datetime: true
  validates :ends_at_before_type_cast, datetime: true
  validate :cannot_add_private_devices_of_other_users
  validate :start_date_is_before_end_date

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "description", "ends_at", "id", "is_test", "name", "owner_id", "starts_at", "status", "updated_at"]
  end

  def active
    active?
  end

  def active?
    (!starts_at || Time.now >= starts_at) && (!ends_at || Time.now <= ends_at)
  end

  def last_reading_at
    devices.map(&:last_reading_at).compact.max
  end

  def user_tags
    devices.flat_map(&:user_tags).compact.uniq
  end

  def all_measurements
    devices.flat_map(&:sensors).filter {|s| !s.is_raw? }.map(&:measurement).uniq
  end

  def components_for_measurement(measurement)
    devices.flat_map(&:components).filter {
      |c| c.measurement == measurement && !c.is_raw?
    }.uniq
  end

  def all_devices_online?
    devices.all? { |d| d.online? }
  end

  def all_devices_offline?
    devices.all? { |d| !d.online? }
  end

  def online_device_count
    devices.filter { |d| d.online? }.length
  end

  private

  def cannot_add_private_devices_of_other_users
    private_devices =  devices.select { |device| device.is_private? && device.owner != self.owner }
    if private_devices.any?
      ids = private_devices.map(&:id).join(", ")
      errors.add(:devices, "can't contain private devices owned by other users (ids: #{ids})")
    end
  end

  def start_date_is_before_end_date
    if starts_at && ends_at && ends_at < starts_at
      errors.add(:ends_at, "is before starts_at")
    end
  end
end

app/controllers/ui/application_controller.rb
module Ui
  class ApplicationController < ActionController::Base
    layout "application"
    include SharedControllerMethods

    private

    def add_breadcrumbs(*crumbs)
      crumbs.each do |crumb|
        add_breadcrumb(*crumb)
      end
    end

    def add_breadcrumb(label, url=nil)
      breadcrumbs << Breadcrumb.new(breadcrumbs, label, url)
    end

    def breadcrumbs
      @breadcrumbs ||= []
    end

    def goto_or(url)
      params[:goto].present? ? params[:goto] : url
    end

    helper_method :breadcrumbs
  end
end

app/controllers/ui/devices_controller.rb
module Ui
  class DevicesController < ApplicationController
    def show
      find_device!
      return unless authorize_device! :show?, :show_device_forbidden
      @title = I18n.t(:show_device_title, name: @device.name)
      add_breadcrumbs(
        [I18n.t(:show_user_title, owner: owner_name), ui_user_path(@device.owner.username)],
        [@title, ui_device_path(@device.id)]
      )
    end

    def edit
      find_device!
      return unless authorize_device! :update?, :edit_device_forbidden
      @title = I18n.t(:edit_device_title, name: @device.name)
      add_breadcrumbs(
        [I18n.t(:show_user_title, owner: owner_name), ui_user_path(@device.owner.username)],
        [I18n.t(:show_device_title, name: @device.name), ui_device_path(@device.id)],
        [I18n.t(:edit_breadcrumb), edit_ui_device_path(@device.id)]
      )
    end

    def update
      find_device!
      return unless authorize_device! :update?, :edit_device_forbidden
      if @device.update(device_params)
        flash[:success] = I18n.t(:update_device_success)
        redirect_to goto_or(ui_device_path(@device.id))
      else
        flash[:alert] = I18n.t(:update_device_failure)
        render :edit, status: :unprocessable_entity
      end
    end

    def delete
      find_device!
      return unless authorize_device! :destroy?, :delete_device_forbidden
      @title = I18n.t(:delete_device_title, name: @device.name)
      add_breadcrumbs(
        [I18n.t(:show_user_title, owner: owner_name), ui_user_path(@device.owner.username)],
        [I18n.t(:show_device_title, name: @device.name), ui_device_path(@device.id)],
        [I18n.t(:edit_breadcrumb, name: @device.name), edit_ui_device_path(@device.id)],
        [I18n.t(:delete_breadcrumb, name: @device.name), delete_ui_device_path(@device.id)]
      )
    end

    def destroy
      find_device!
      return unless authorize_device! :destroy?, :delete_device_forbidden
      if @device.name != params[:name]
        flash[:alert] = I18n.t(:delete_device_wrong_name)
        redirect_to delete_ui_device_path(@device.id)
        return
      end
      @device.archive!
      flash[:success] = I18n.t(:delete_device_success)
      redirect_to ui_user_path(current_user.username)
    end

    def download
      find_device!
      return unless authorize_device! :download?, :download_device_forbidden
      @title = I18n.t(:download_device_title, name: @device.name)
      add_breadcrumbs(
        [I18n.t(:show_user_title, owner: owner_name), ui_user_path(@device.owner.username)],
        [I18n.t(:show_device_title, name: @device.name), ui_device_path(@device.id)],
        [I18n.t(:download_breadcrumb), download_ui_device_path(@device.id)]
      )
    end

    def download_confirm
      find_device!
      return unless authorize_device! :download?, :download_device_forbidden
      if @device.request_csv_archive_for!(current_user)
        flash[:success] = I18n.t(:download_device_success)
      else
        flash[:alert] = I18n.t(:download_device_requested_too_soon)
      end
      redirect_to goto_or(ui_device_path(@device.id))
    end

    def register
      unless current_user
        flash[:alert] = I18n.t(:register_device_forbidden)
        redirect_to login_path
        return
      end
      @title = I18n.t(:register_device_title)
      add_breadcrumbs(
        [I18n.t(:show_user_title, owner: owner_name), ui_user_path(current_user)],
        [@title, register_ui_devices_path]
      )
    end

    def new
      unless current_user
        flash[:alert] = I18n.t(:register_device_forbidden)
        redirect_to login_path
        return
      end
      @title = I18n.t(:new_device_title)
      add_breadcrumbs(
        [I18n.t(:show_user_title, owner: owner_name), ui_user_path(current_user)],
        [I18n.t(:register_device_title), register_ui_devices_path],
        [I18n.t(:legacy_breadcrumb), new_ui_device_path]
      )
      @device = Device.new(owner: current_user)
    end

    def onboarding
      unless current_user
        flash[:alert] = I18n.t(:register_device_forbidden)
        redirect_to login_path
        return
      end
      @title = I18n.t(:new_device_title)
      add_breadcrumbs(
        [I18n.t(:show_user_title, owner: owner_name), ui_user_path(current_user)],
        [I18n.t(:register_device_title), register_ui_devices_path],
        [I18n.t(:legacy_breadcrumb), new_ui_device_path]
      )
    end

    def create
      unless current_user
        flash[:alert] = I18n.t(:register_device_forbidden)
        redirect_to login_path
        return
      end
      @device = new_device(device_params)
      if @device.valid?
        @device.save
        flash[:success] = I18n.t(:new_device_success)
        redirect_to ui_device_path(@device.id)
      else
        flash[:alert] = I18n.t(:new_device_failure)
        render :new, status: :unprocessable_entity
      end
    end

    def onboarding_create
      unless current_user
        flash[:alert] = I18n.t(:register_device_forbidden)
        redirect_to login_path
        return
      end
      @devices = devices_params[:device].map do |attrs|
        new_device(attrs)
      end
      if @devices.all?(&:valid?)
        @devices.each(&:save)
        flash[:success] = I18n.t(:new_device_success)
        redirect_to ui_user_path(current_user)
      else
        flash[:alert] = I18n.t(:new_device_failure)
        render :onboarding, status: :unprocessable_entity
      end

    end

    def upload
      find_device!
      return unless authorize_device! :upload?, :upload_device_forbidden
      @title = I18n.t(:upload_device_title, name: @device.name)
      add_breadcrumbs(
        [I18n.t(:show_user_title, owner: owner_name), ui_user_path(@device.owner.username)],
        [I18n.t(:show_device_title, name: @device.name), ui_device_path(@device.id)],
        [I18n.t(:upload_breadcrumb), download_ui_device_path(@device.id)]
      )
    end

    def upload_readings
      find_device!
      return unless authorize_device! :upload?, :upload_device_forbidden
      params[:data_files].each do |file|
        CSVUploadJob.perform_later(@device.id, file.read)
      end
      flash[:success] = I18n.t(:upload_device_success)
      redirect_to goto_or(ui_device_path(@device.id))

    end


    private

    def new_device(attrs)
      device = Device.new(attrs)
      device.owner = current_user
      device
    end

    def devices_params
      params.require(:devices).permit(
        device: device_param_names
      )
    end

    def device_params
      params.require(:device).permit(
        *device_param_names
      )
    end

    def device_param_names
      [
        :name,
        :description,
        :exposure,
        :latitude,
        :longitude,
        :is_private,
        :precise_location,
        :enable_forwarding,
        :notify_low_battery,
        :notify_stopped_publishing,
        :hardware_version_override,
        :mac_address,
        :device_token,
        :forwarding_destination_id,
        { :tag_ids => [] },
        { :postprocessing_attributes => :hardware_url },
      ]
    end

    def find_device!
      @device = Device.find(params[:id])
    end

    def authorize_device!(action, alert)
      return true if authorize? @device, action
      flash[:alert] = I18n.t(alert)
      redirect_to current_user ? ui_user_path(current_user.username) : login_path
      return false
    end

    def owner_name(capitalize=true)
      owner = @device&.owner || current_user
      helpers.possessive(owner, current_user, capitalize: capitalize, third_person: true)
    end
  end
end

app/controllers/ui/sessions_controller.rb
module Ui
  class SessionsController < ApplicationController
    include SharedControllerMethods
    require 'uri'
    require 'net/http'
    require 'net/https'

    def new
      @title = I18n.t(:new_session_title)
      redirect_to ui_users_url if current_user
    end

    def index
      redirect_to new_ui_session_path
    end

    def create
      if params[:send_password_email]
        reset_password_email
        redirect_to new_ui_session_path
        return
      end

      user = User.where("lower(email) = lower(?) OR lower(username) = lower(?)",
                        params[:username_or_email], params[:username_or_email]).first
      if user && user.authenticate_with_legacy_support(params[:password])
        session[:user_id] = user.id

        if params[:goto].include? 'discourse'
          redirect_to session[:discourse_url]
        else
          flash[:success] = I18n.t(:new_session_success)
          redirect_to goto_or(session[:user_return_to] || ui_users_path)
        end
      else
        flash.now.alert = I18n.t(:new_session_failure)
        render "new"
      end
    end

    def reset_password_email
      user = User.where("lower(email) = lower(?) OR lower(username) = lower(?)",
                        params[:username_or_email], params[:username_or_email]).first

      if user
        authorize user, :request_password_reset?
        user.send_password_reset
      end
      flash[:notice] = I18n.t(:password_reset_notice)
    end

    def password_reset_landing
      @title = I18n.t(:password_reset_landing_title)
      @token = params[:token]
    end

    def change_password
      @token = params.require(:token)

      if params.require(:password) != params.require(:password_confirmation)
        flash[:alert] = I18n.t(:password_reset_failure)
        render "password_reset_landing"
        return
      end

      @user = User.find_by(password_reset_token: @token)
      if @user
        authorize @user, :update_password?
        @user.update(params.permit(:password, :password_confirmation).merge(password_reset_token: nil))
        flash[:success] = I18n.t(:password_reset_success, username: @user.username)
        redirect_to new_ui_session_path
      else
        flash[:alert] = I18n.t(:password_reset_invalid)
        render "password_reset_landing"
      end
    end

    def destroy
      session[:user_id] = nil
      redirect_to goto_or(login_url), notice: I18n.t(:destroy_session_success)
    end
  end
end

app/controllers/ui/static_controller.rb
module Ui
  class StaticController < ApplicationController
    def policy
    end
  end
end

app/views/ui/experiments/_actions.html.erb
<% button_class = local_assigns[:dark_buttons] ? "btn-dark" : "btn-secondary" %>
<p class="mb-0">
  <% if authorize? experiment, :update? %>
    <%= sc_nav_button_to(t(:show_experiment_edit_cta, name: experiment.name), edit_ui_experiment_path(experiment, goto: request.path), local_assigns) %>
  <% end %>
</p>

app/views/ui/experiments/_devices_collection.html.erb
<%= render layout: "ui/shared/box", locals: { no_padding: true } do %>
  <div class="p-3" id="devices">
    <h2><%= t :experiment_devices_collection_heading %></h2>
    <% if devices.length < 1 %>
      <p><%= t :experiment_devices_collection_no_devices_message %></p>
    <% end %>
  </div>
  <div class="<%= devices.total_pages > 1 ? "border-bottom": "" %>">
  <%= render partial: "ui/devices/device", collection: devices.by_last_reading, locals: { with_actions: true } %>
  </div>
  <% if devices.total_pages > 1 %>
    <div class="w-100 mt-3 pagination-container">
      <div class="mx-auto width-fit-content">
        <%= paginate devices, param_name: :device_page, theme: "bootstrap-5" %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/ui/experiments/_experiment.html.erb
<div class="experiment listing row map-container border-top g-0 z-0">
  <%= link_to(ui_experiment_path(experiment.id), class: "listing-link z-1") do %>
    <span class="sr-only"><%= experiment.name %></span>
  <% end %>
  <div class="col-12 col-md-3">
    <%= render partial: "ui/shared/map",
      locals: {
        points: experiment.devices.map { |d| { lat: d.latitude, lng: d.longitude } },
        class: "experiment",
        marker_url: asset_url("map-pin-experiment.svg")
      }
    %>
  </div>
  <div class="col-12 col-md-9 p-3 pb-4 darker">
    <h3 class="mb-1 text-break"><%= experiment.name %></h3>
    <%= render partial: "ui/experiments/meta", locals: { experiment: experiment, hide_owner: local_assigns[:hide_owner] } %>
    <% if local_assigns[:with_actions] %>
      <div class="mt-4 z-2 position-relative">
        <%= render partial: "ui/experiments/actions", locals: { experiment: experiment } %>
      </div>
    <% end %>
  </div>
</div>

app/views/ui/experiments/_fields.html.erb
<div class="mb-5">
  <h2 class="mb-4"><%= t(:experiment_form_details_subhead) %></h2>
  <%= form.text_field :name %>
  <%= form.text_field :description %>
  <%= form.text_field :starts_at, class: "flatpickr" %>
  <%= form.text_field :ends_at, class: "flatpickr" %>
</div>
<div class="mb-5">
  <h2 class="mb-4"><%= t(:experiment_form_devices_subhead) %></h2>
  <div class="devices-typeahead">
    <%= label_tag "device_search", t(:experiment_form_search_devices_label), class: "form-label" %>
    <%= text_field_tag :device_search, "", class: "form-control device-search", autocomplete: "off" %>
    <%= hidden_field_tag "experiment[device_ids][]", "" %>
    <div class="mt-3 container-lg devices-list border border-medium rounded <%= "d-none" unless experiment.devices.any? %>">
      <% experiment.devices.each do |device| %>
        <%= render partial: "ui/devices/select_list_item", locals: {
          value: device.id,
          name: "experiment[device_ids][]",
          title: device.name,
          owner: device.owner&.username,
          location: device.location_string,
          description: device.description
      } %>
      <% end %>
    </div>
    <template id="device-template">
      <%= render partial: "ui/devices/select_list_item", locals: { name: "experiment[device_ids][]", hide_remove_button: true } %>
    </template>
  </div>
</div>
<% if current_user&.is_admin? %>
  <div class="mb-5">
    <h2 class="mb-4"><%= t(:experiment_form_admin_options_subhead) %></h2>
    <%= form.check_box :is_test, label: t(:experiment_form_is_test_label) %>
  </div>
<% end %>

app/views/ui/experiments/_header.html.erb
<% content_for :profile_header_image do %>
  <div class="circular-image-crop image-border">
    <%= render partial: "ui/shared/map",
      locals: {
        points: experiment.devices.map { |d| { lat: d.latitude, lng: d.longitude } },
        class: "experiment",
        marker_url: asset_url("map-pin-experiment.svg")
      }
    %>
  </div>
<% end %>
<% content_for :profile_header_meta do %>
  <%= render partial: "ui/experiments/meta",  locals: { experiment: experiment } %>
<% end %>
<% content_for :profile_header_actions do %>
  <%= render partial: "ui/experiments/actions", locals: { experiment: experiment, dark_buttons: true} %>
<% end %>
<%= render partial: "ui/shared/profile_header", locals: { title: t(:show_experiment_title, name: experiment.name), title_link: ui_experiment_path(experiment.id) } %>

app/views/ui/experiments/_meta.html.erb
<p class="mb-0 device-status <%= device_collection_status_class(experiment) %>">
  <span class="pe-1"><%= show_svg("status_icon.svg") %></span>
  <strong><%= pluralize(experiment.devices.length, t(:experiment_meta_device_noun)) %> (<%= experiment.online_device_count %> <%= t(:experiment_meta_online_adjective) %>)</strong>
</p>
<% unless local_assigns[:hide_owner] %>
  <p class="mb-0">
  <span class="pe-1"><%= show_svg("user_details_icon_light.svg") %></span>
    <%= link_to(experiment.owner.username, ui_user_path(experiment.owner.username), class: "d-inline-block position-relative subtle-link z-3") %>
  </p>
<% end %>
<p class="mb-0">
  <span class="pe-1"><%= show_svg("clock-fill.svg") %></span>
  <% if experiment.last_reading_at %>
    <%= t :device_meta_last_reading_at, time: time_ago_in_words(local_time_zone.at(experiment.last_reading_at)) %>
  <% else %>
    <%= t :device_meta_no_readings_message %>
  <% end %>
</p>

app/views/ui/experiments/_page_nav.html.erb
<div class="w-100 gx-0">
  <%= render layout: "ui/shared/box", locals: { no_padding: true, class: "w-100 sticky-lg-top z-2 page-nav", no_shadow: true } do %>
    <% if current_page?(controller: :experiments, action: :readings) %>
      <a href="<%= ui_experiment_path(experiment) %>" class="subtle-link d-block p-3"><%= t :experiment_page_nav_devices %></a>
      <p class="d-block p-3 mb-0 border-top"><strong><%= t :experiment_page_nav_readings_heading %></strong></p>
      <% experiment.all_measurements.each do |measurement| %>
        <% if params[:measurement_id]&.to_i == measurement.id %>
          <p class="d-block p-3 ps-5 mb-0 border-top"><strong><%= measurement.name %></strong></p>
        <% else %>
          <a href="<%= readings_ui_experiment_path(experiment, measurement_id: measurement.id) %>" class="subtle-link d-block p-3 ps-5 border-top"><%= measurement.name %></a>
        <% end %>
      <% end %>
    <% else %>
      <p class="mb-0 d-block p-3"><strong><%= t :experiment_page_nav_devices %></strong></p>
      <a href="<%= readings_ui_experiment_path(experiment) %>" class="subtle-link d-block p-3 border-top"><%= t :experiment_page_nav_readings_heading %></a>
  <% end %>
<% end %>
</div>

app/views/ui/experiments/delete.html.erb
<%= render partial: "ui/experiments/header", locals: { experiment:  @experiment } %>
<%= render layout: "ui/shared/form_container", locals: { title: t(:delete_experiment_header), box_inner_class: "drop-shadow-teal" } do %>
  <%= bootstrap_form_tag url: ui_experiment_path(@experiment.id), method: :delete do |f| %>
    <p><%= t(:delete_experiment_warning_html, name: @experiment.name) %></p>
    <%= f.text_field :name, label: t(:delete_experiment_name_label)  %>
    <div class="mt-4">
      <%= f.primary t(:delete_experiment_submit), class: "btn btn-danger w-100 w-md-auto" %>
    </div>
  <% end %>
<% end %>

app/views/ui/experiments/edit.html.erb
<%= render partial: "ui/experiments/header", locals: { experiment:  @experiment } %>
<%= render layout: "ui/shared/form_container", locals: { title: t(:edit_experiment_header), box_inner_class: "drop-shadow-teal" } do %>
  <%= bootstrap_form_for @experiment, url: ui_experiment_path(@experiment) do |form| %>
    <%= hidden_field_tag :goto, params[:goto] %>
    <% @experiment.errors.each do |attr, msg| %>
      <%= "#{attr} #{msg}" if @experiment.errors[attr].first == msg %>
    <% end %>
    <%= render partial: "fields", locals: { experiment: @experiment, form: form } %>
    <%= render partial: "ui/shared/form_buttons", locals: { form: form, back_href: ui_experiment_path(@experiment.id), submit_label: t(:edit_experiment_submit) } %>
  <% end %>
  <% if authorize? @experiment, :destroy? %>
    <%= render layout: "ui/shared/danger_zone" do %>
      <div><%= link_to t(:edit_experiment_delete_experiment_submit), delete_ui_experiment_path(@experiment.id), class: "btn btn-danger w-100 w-md-25 justify-content-center" %></div>
    <% end %>
  <%  end %>
<% end %>

app/views/ui/experiments/new.html.erb
<%= render partial: "ui/users/header", locals: { user:  current_user } %>
<%= render layout: "ui/shared/form_container" do %>
  <p class="mb-4"><%= t(:new_experiment_blurb) %></p>
  <%= bootstrap_form_for @experiment, url: ui_experiments_path do |form| %>
    <%= render partial: "fields", locals: { experiment: @experiment, form: form, include_hardware_info: true } %>
    <%= render partial: "ui/shared/form_buttons", locals: { form: form, back_href: ui_user_path(current_user.username), submit_label: t(:new_experiment_submit) } %>
  <% end %>
<% end %>

app/views/ui/experiments/readings.html.erb
<%= render partial: "ui/experiments/header", locals: { experiment:  @experiment } %>

<% content_for :two_column_sidebar do %>
  <%= render partial: "ui/experiments/page_nav", locals: { experiment:  @experiment } %>
<% end %>

<% content_for :two_column_main do %>
  <%= render layout: "ui/shared/box", locals: { inner_class: "p-3 pb-0 drop-shadow-teal", class: "mb-5", no_padding: true } do %>
    <h2 class="mb-3"><%= @measurement.name %></h2>
    <p class="mb-5"><%= @measurement.description %>
    <% @experiment.components_for_measurement(@measurement).each do |component| %>
      <%= render partial: "ui/shared/reading", locals: {
        class: "experiment",
        component: component,
        title: component.device.name,
        title_link: ui_device_path(component.device.id),
        description: false,
        to: @experiment.last_reading_at,
        sync_all_on_page: true
      } %>
    <% end %>
  <% end %>
<% end %>
<%= render partial: "ui/shared/two_column" %>