config/routes.rb
require "sidekiq/web"
Rails.application.routes.draw do
  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == ENV["sidekiq_username"] && password == ENV["sidekiq_password"]
    end
  end
  mount Sidekiq::Web, at: "/sidekiq"

  get "discourse/sso" => 'discourse#sso'

  get "login", to: redirect("/ui/sessions/new")
  get "logout", to: redirect("/ui/sessions/destroy")
  get "password_reset/:token", to: redirect("/ui/password_reset/%{token}")

  namespace "ui" do
    get "/", to: redirect("/ui/users")

    get "/policy", to: "static#policy"

    constraints id: /[^\/]+/ do
      # Explicitly override to allow usernames with dots.
      # See:https://stackoverflow.com/questions/5369654/why-do-routes-with-a-dot-in-a-parameter-fail-to-match
      resources :users, as: "users" do
        member do
          get :delete
          get :edit
          get :secrets
        end
        collection do
          get :post_delete
        end
      end
    end

    resources :devices, as: "devices" do
      member do
        get :edit
        get :delete
        get :download
        get :upload
        post :upload, to: "devices#upload_readings"
        post :download, to: "devices#download_confirm"
      end
      collection do
        get :register
        get :new
        post :create
        get :onboarding
        post :onboarding, to: "devices#onboarding_create"
      end
    end

    resources :experiments, as: "experiments" do
      member do
        get :readings
        get :delete
      end
    end

    get "sessions/destroy", to: "sessions#destroy"
    resources :sessions, as: "sessions"
    post 'change_password', to: 'sessions#change_password', as: 'change_password'
    get 'password_reset/:token', to: 'sessions#password_reset_landing', as: 'password_reset'
  end

  api_version(module: "V1", path: { value: "v1" }, header: {name: "Accept", value: "application/vnd.smartcitizen; version=1"}, defaults: { format: :json }) do
    resources :devices
  end

  api_version(module: "V0", path: {value: "v0"}, header: {name: "Accept", value: "application/vnd.smartcitizen; version=0"}, default: true, defaults: { format: :json }) do
    # devices
    resources :devices do
      member do
        resources :readings, only: [:index, :create] do
          get 'csv_archive', on: :collection
        end
      end
      get 'world_map', on: :collection
      get 'fresh_world_map', on: :collection
    end
    # readings
    match "add" => "readings#legacy_create", via: [:get, :post, :patch, :put]
    match "datetime" => "readings#datetime", via: [:get, :post, :patch, :put]

    resources :sensors, except: [:destroy]
    resources :components, only: [:show, :index]
    resources :sessions, only: :create
    resources :experiments

    resources :tag_sensors
    resources :tags
    resources :measurements

    constraints id: /[^\/]+/ do
      # Explicitly override to allow usernames with dots.
      # See:https://stackoverflow.com/questions/5369654/why-do-routes-with-a-dot-in-a-parameter-fail-to-match
      resources :users
    end
    resources :password_resets, only: [:show, :create, :update]
    resources :oauth_applications, path: 'applications'
    get :forward, to: "forwarding#authorize"

    resources :me, only: [:index] do
      patch '/' => 'me#update', on: :collection
      put '/' => 'me#update', on: :collection
      delete '/' => 'me#destroy', on: :collection
    end

    # onboarding process
    namespace :onboarding do
      get 'device', to: 'orphan_devices#show'
      post 'device', to: 'orphan_devices#create'
      patch 'device', to: 'orphan_devices#update'
      post 'user', to: 'device_registrations#find_user'
      post 'register', to: 'device_registrations#register_device'
    end

    get "discourse/sso" => 'discourse#sso'
    get 'search' => 'static#search'
    get 'metrics' => 'static#metrics'
    # use_doorkeeper
    # root to: 'static#home'
    get '/', to: 'static#home'
    get '/version', to: "static#version"
    get "/404" => "errors#not_found"
    get "/500" => "errors#exception"
    get "/test_error" => "errors#test_error"

    # Active Storage cannot show the correct url if using catchall matchers
    # https://github.com/rails/rails/issues/31228
    # Disable until a solution is found
    #match "*path", to: "errors#not_found", via: :all
  end

  # get '*path', :to => redirect("/v0/%{path}")
  # root to: redirect('/v0')

end

app/views/layouts/_breadcrumbs.html.erb
<nav aria-label="breadcrumb" class="breadcrumbs mb-2 mb-lg-0">
  <ul class="breadcrumb mb-lg-0 d-lg-flex align-items-center">
    <% breadcrumbs.each_with_index do |breadcrumb, index| %>
      <% active = index == breadcrumbs.length - 1 %>
      <li class="breadcrumb-item <%= "active" if breadcrumb.active? %>" <%= "aria-current=\"page\"" if breadcrumb.active? %>>
        <% if breadcrumb.url %>
          <a href="<%= breadcrumb.url %>">
            <%= breadcrumb.label %>
          </a>
        <% else %>
          <%= breadcrumb.label %>
        <% end %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/layouts/_doorbell_embed.html.erb
<script type="text/javascript">
    window.doorbellOptions = {
        "id": "1904",
        "appKey": "epGCzRsQjOyOPslP2rONu5XUVwoAAKY4yQZy21baD3Sb0RolnuBi6G9H4Kd9tgzG",
        "hideButton": false,
    };
    (function(w, d, t) {
        var hasLoaded = false;
        function l() { if (hasLoaded) { return; } hasLoaded = true; window.doorbellOptions.windowLoaded = true; var g = d.createElement(t);g.id = 'doorbellScript';g.type = 'text/javascript';g.crossorigin = 'anonymous';g.async = true;g.src = 'https://embed.doorbell.io/button/'+window.doorbellOptions['id']+'?t='+(new Date().getTime());(d.getElementsByTagName('head')[0]||d.getElementsByTagName('body')[0]).appendChild(g); }
        if (w.attachEvent) { w.attachEvent('onload', l); } else if (w.addEventListener) { w.addEventListener('load', l, false); } else { l(); }
        if (d.readyState == 'complete') { l(); }
    }(window, document, 'script'));
</script>

app/views/layouts/_flashes.html.erb
<% flash.each do |name, msg| %>
  <div class="<%= [flash_class(name), "sticky-top z-5 mx-2 mx-lg-3 mb-3 alert-dismissable fade show"].join(" ") %>">
    <div class="container-lg px-0 d-flex justify-content-between">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss=alert aria-label="Close"></button>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="bg-black text-white mt-5 pt-3 pt-lg-5 pb-3">
  <div class="container-lg px-0">
    <div class="row g-0 g-lg-2 d-flex flex-lg-row flex-column align-items-center justify-content-lg-between  mb-0 mb-lg-5 px-4 px-lg-0">
      <div class="w-auto mb-3 mb-lg-0 mx-0 g-0">
        <img style="height: 80px; pointer-events: auto;" src="<%= image_url("smartcitizen_logo2.svg") %>" alt="<%= t :footer_logo_alt %>">
      </div>
      <div class="w-auto mb-3 mb-lg-0 mx-0 g-0">
        <div class="outlined-box p-3 row g-0 align-items-center width-fit-content mx-1 mx-lg-0">
          <div class="col-auto"><%= t :footer_attribution %></div>
          <div class="col-auto">
            <img height="36" src="<%= image_url("logo_fablab_bcn_small.png") %>" alt="<%= t :footer_fablab_alt %>" />
          </div>
          <div class="col-auto">
            <img height="16" src="<%= image_url("iaac.png") %>" alt="<%= t :footer_iaac_alt %>">
          </div>
        </div>
      </div>
      <div class="w-auto mb-3 mb-lg-0 mx-0 g-0">
        <div class="row align-items-center justify-content-center justify-content-lg-space-around width-fit-content">
          <div class="col-auto d-flex mb-3 mb-lg-0 justify-content-space-around flex-direction-column">
            <img height="48" src="<%= image_url("eu_flag.png") %>" alt="" />
          </div>
          <div class="col-auto d-flex justify-content-space-around text-center text-lg-start flex-direction-column">
            <p class="mb-0 ts-and-cs"><%= t :footer_funding_html %></p>
          </div>
        </div>
      </div>
      <div class="w-auto mb-5 mb-lg-0 mx-0 g-0">
          <p class="mb-1"><small><%= t :footer_monitoring %></small></p>
          <a href="<%= t :footer_uptimerobot_url %>" target="_blank"><img height="20" class="w-auto" src="<%= image_url("uptimerobot-logo.svg") %>" alt="UptimeRobot"  /></a>
      </div>
    </div>
    <div class="row g-0 text-lg-center px-3 px-lg-0 mx-0 g-0">
      <p class="ts-and-cs"><%= t :footer_licence_html %></p>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<div class="bg-black m-2 sticky-top nav-container z-4 py-1 mx-lg-3">
  <nav class="navbar navbar-dark">
    <div class="container-lg px-3 px-lg-0">
      <a class="navbar-brand" href="https://www.smartcitizen.me">
        <img src="<%= image_url("smartcitizen_logo.svg") %>" alt="<%= t :logo_alt %>" width="36" height ="36" />
      </a>
      <% if breadcrumbs.length >= 1 %>
        <div class="px-3 px-lg-0 d-none d-lg-block">
          <%= render partial: "layouts/breadcrumbs" %>
        </div>
      <% end %>

      <ul class="navbar-nav ms-auto me-2 me-lg-0 d-flex flex-row ">
      <li class="nav-item d-none d-md-flex">
        <a class="nav-link btn btn-navbar" target="_blank" href="<%= t :kit_link_url %>"><%= t :kit_link_text %></a>
      </li>
      <% if current_user %>
          <li class="nav-item">
            <a class="nav-link ms-3 ms-lg-5" title="<%= t :profile_pic_alt_text %>" href="<%= ui_user_path(current_user.username) %>">
              <%= render partial: "ui/users/profile_image", locals: {
                user: current_user,
                alt: t(:profile_pic_alt_text),
                class: "navbar-profile-image"
              } %>
            </a>
          </li>
      <% else %>
        <li class="nav-item me-lg-4">
          <a class="nav-link ms-3 ms-lg-5" href="<%= login_url %>"><%= t :login_link_text %></a>
        </li>
      <% end %>
        </ul>
      <button class="navbar-toggler pe-0 ps-3 ms-lg-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMenuToggle" aria-controls="navbarMenuToggle" aria-expanded="false" aria-label="<%= t :hamburger_label %>">
        <i class="fa-solid fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarMenuToggle">
        <ul class="navbar-nav ms-auto mt-2 mt-md-0">
          <li class="nav-item  d-md-none">
            <a class="nav-link btn btn-navbar w-100 w-md-auto text-center text-lg-end ms-auto" target="_blank" href="<%= t :kit_link_url %>">
              <span data-bs-toggle="collapse" data-bs-target="#navbarMenuToggle" >
                <%= t :kit_link_text %>
              </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link w-100 w-md-auto text-center text-lg-end ms-auto" target="_blank" href="<%= map_base_url %>">
              <span data-bs-toggle="collapse" data-bs-target="#navbarMenuToggle" >
                <%= t :map_link_text %>
              </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link w-100 w-md-auto text-center text-lg-end ms-auto" target="_blank" href="<%= t :documentation_link_url %>">
              <span data-bs-toggle="collapse" data-bs-target="#navbarMenuToggle" >
                <%= t :documentation_link_text %>
              </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link w-100 w-md-auto text-center text-lg-end ms-auto" target="_blank" href="<%= t :forum_link_url %>">
              <span data-bs-toggle="collapse" data-bs-target="#navbarMenuToggle" >
                <%= t :forum_link_text %>
              </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link w-100 w-md-auto text-center text-lg-end ms-auto" target="_blank" href="<%= t :api_link_url%>">
              <span data-bs-toggle="collapse" data-bs-target="#navbarMenuToggle" >
                <%= t :api_link_text %>
              </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link w-100 w-md-auto text-center text-lg-end ms-auto" target="_blank" href="<%= t :about_link_url%>">
              <span data-bs-toggle="collapse" data-bs-target="#navbarMenuToggle" >
                <%= t :about_link_text %>
              </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link w-100 w-md-auto text-center text-lg-end ms-auto" href="<%= t :policy_link_url%>">
              <span data-bs-toggle="collapse" data-bs-target="#navbarMenuToggle" >
                <%= t :policy_link_text %>
              </span>
            </a>
          </li>
          <% if current_user %>
            <li class="nav-item">
              <a class="nav-link w-100 w-md-auto text-center text-lg-end ms-auto link-danger" href="<%= logout_path %>">
                <span data-bs-toggle="collapse" data-bs-target="#navbarMenuToggle" >
                  <%= t :logout_link_text %>
                </span>
              </a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <% if breadcrumbs.length > 1 %>
    <div class="container-lg px-3 px-lg-0 d-lg-none">
      <%= render partial: "layouts/breadcrumbs" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.erb
<% content_for :container do %>
  <div class="container mx-2 mx-md-auto w-auto w-md-100 mt-2 md-md-5 g-0">
    <div class="bg-white w-100 px-4 pb-5 pt-4 border border-thick">
      <% if @title %>
        <header>
          <h1 class="mb-4"><%= @title %></h1>
        </header>
      <% end %>
      <main>
        <%= yield %>
      </main>
    </div>
  </div>
<% end  %>
<%= render layout: "base" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= [t(:title), @title].compact.join(" – ") %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script defer data-domain="api.smartcitizen.me" src="https://plausible.io/js/script.js"></script>
  </head>
  <body>
    <%= render partial: "layouts/nav" %>
    <%= render partial: "layouts/flashes" %>
    <main>
      <%= content_for?(:container) ? yield(:container) : yield %>
    </main>
    <%= render partial: "layouts/footer" %>
    <%= render partial: "layouts/doorbell_embed" %>
  </body>
</html>